### ISSUE TITLE
exe!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [KXRXH/SpotifyMusicDownloader#3]
hello and thanks for this programm!but there is no any spotify exe!!!please help me!!!

**Comment by KXRXH** [comment]
what do you mean there is no any spotify exe?

**Comment by KXRXH** [comment]
> hello and thanks for this programm!but there is no any spotify exe!!!please help me!!!

what do you mean there is no any spotify exe?

**Comment by KXRXH** [comment]
> hello and thanks for this programm!but there is no any spotify exe!!!please help me!!!

<img width="517" alt="image" src="https://user-images.githubusercontent.com/74421236/161389478-4e2031f3-d369-46b1-93d4-454cd7144808.png">
You need to run SpotifyDownloader.exe in .rar archive.

**Comment by KENPOKASMMA1982** [comment]
BUT I DONT SEE ANY ARCHIVE  SpotifyDownloader.exe
